# Generated by Django 5.2 on 2026-02-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='athlet',
            new_name='athlete',
        ),
    ]
