# Generated by Django 5.2 on 2026-02-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_rename_athlet_run_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Запуск'), ('in_progress', 'Выполняется'), ('finished', 'Закончен')], default='init', max_length=20),
        ),
    ]
