# Generated by Django 5.2 on 2026-02-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_run_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
