# Generated by Django 5.2 on 2026-02-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='name',
            new_name='full_name',
        ),
    ]
