# Generated by Django 5.2 on 2026-02-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
