# Generated by Django 5.2 on 2026-02-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_collectibleitem_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
