# Generated by Django 5.2 on 2026-02-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_collectibleitem_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=250),
        ),
    ]
